games:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\GameController

player_roles:
    type:     rest
    parent:   games
    resource: Lain\OneNightWerewolfBundle\Controller\PlayerRoleController
