games:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\GameController

player_roles:
    type:     rest
    resource: @LainOneNightWerewolfBundle/Resources/config/player_roles_routes.yml