games:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\GameController

game_players:
    type:     rest
    parent:   games
    resource: Lain\OneNightWerewolfBundle\Controller\GamePlayerController
