games:
    type:     rest
    resource: @LainOneNightWerewolfBundle/Resources/config/games_routes.yml

players:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\PlayerController

roles:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RoleController

rooms:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RoomController

