lain_one_night_werewolf_homepage:
    path:     /hello/{name}
    defaults: { _controller: LainOneNightWerewolfBundle:Default:index }

rooms:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RoomController

roles:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RoleController

regulations:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RegulationController