lain_one_night_werewolf_homepage:
    path:     /hello/{name}
    defaults: { _controller: LainOneNightWerewolfBundle:Default:index }

rooms:
    type:     rest
    resource: @LainOneNightWerewolfBundle/Resources/config/rooms_routes.yml

roles:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RoleController

regulations:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RegulationController