games:
    type:     rest
    resource: @LainOneNightWerewolfBundle/Resources/config/games_routes.yml

players:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\PlayerController

regulations:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RegulationController

roles:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RoleController

rooms:
    type:     rest
    resource: Lain\OneNightWerewolfBundle\Controller\RoomController

